http:
  middlewares:
    authelia:
      forwardAuth:
        address: http://authelia.service.consul:9091/api/authz/forward-auth
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Email
          - Remote-Name
  routers:
    traefik-dashboard:
      entryPoints:
        - web
        - websecure
      rule: Host(`traefik.ops.home.arpa`)
      service: api@internal
      tls: {}
    consul-dashboard:
      entryPoints:
        - web
        - websecure
      rule: Host(`consul.ops.home.arpa`)
      service: consul-dashboard
      tls: {}
    pihole-dashboard:
      entryPoints:
        - web
        - websecure
      rule: Host(`pihole.ops.home.arpa`)
      service: pihole-dashboard
      tls: {}
  services:
    consul-dashboard:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:8500
    pihole-dashboard:
      loadBalancer:
        servers:
          - url: http://10.10.10.10:8080

tls:
  certificates:
    - certFile: /etc/traefik/certs/server.crt
      keyFile: /etc/traefik/certs/server.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/server.crt
        keyFile: /etc/traefik/certs/server.key
