---
- name: Read defined libvirt networks
  ansible.builtin.command:
    argv:
      - virsh
      - net-list
      - --all
      - --name
  register: defined_networks_result
  changed_when: false
  check_mode: false

- name: Define missing libvirt networks
  ansible.builtin.command:
    argv:
      - virsh
      - net-define
      - /dev/stdin
    stdin: "{{ lookup('ansible.builtin.template', 'network.xml.j2') }}"
  loop: "{{ networks }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.name not in defined_networks_result.stdout_lines

- name: Read libvirt network state and autostart settings
  ansible.builtin.command:
    argv:
      - virsh
      - net-info
      - "{{ item.name }}"
  loop: "{{ networks }}"
  loop_control:
    label: "{{ item.name }}"
  register: network_info_results
  changed_when: false
  check_mode: false

- name: Start networks
  ansible.builtin.command:
    argv:
      - virsh
      - net-start
      - "{{ item.item.name }}"
  loop: "{{ network_info_results.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: item.stdout is not regex('(?m)^Active:\\s+yes$')

- name: Enable networks at boot
  ansible.builtin.command:
    argv:
      - virsh
      - net-autostart
      - "{{ item.item.name }}"
  loop: "{{ network_info_results.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: item.stdout is not regex('(?m)^Autostart:\\s+yes$')
