---
- name: Set base image paths
  ansible.builtin.set_fact:
    vm_image_directory: "{{ storage_root }}/images"
    vm_base_image_path: "{{ storage_root }}/images/debian-12-genericcloud-amd64-20260909-2596.qcow2"

- name: Create image directory
  ansible.builtin.file:
    path: "{{ vm_image_directory }}"
    state: directory
    owner: root
    group: kvm
    mode: "0755"

- name: Download base image
  ansible.builtin.get_url:
    url: https://cloud.debian.org/images/cloud/bookworm/20260909-2596/debian-12-genericcloud-amd64-20260909-2596.qcow2
    dest: "{{ vm_base_image_path }}"
    checksum: sha512:08fea112563461f251f3c95a5c5cf8cb25eb60f74cec03e85a97ff91d3efef3059d35837598bbb476008f20db6d3bdc7143c5f2f2a9a6da394a0acc601fd5986
    owner: root
    group: kvm
    mode: "0644"
