---
- name: Create nftables configuration directory
  ansible.builtin.file:
    path: /etc/nftables.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install NAT rules
  ansible.builtin.template:
    src: nat.nft.j2
    dest: /etc/nftables.d/homelab-router.nft
    owner: root
    group: root
    mode: "0644"
    validate: /usr/sbin/nft -c -f %s
  register: nat_rules_result

- name: Install routing and NAT service
  ansible.builtin.template:
    src: router.service.j2
    dest: /etc/systemd/system/homelab-router.service
    owner: root
    group: root
    mode: "0644"
  register: router_service_result

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: router_service_result.changed

- name: Enable routing and NAT service
  ansible.builtin.systemd_service:
    name: homelab-router.service
    enabled: true
    state: "{{ 'restarted' if nat_rules_result.changed or router_service_result.changed else 'started' }}"
