---
- name: Prepare SSH access to guests
  ansible.builtin.import_tasks: ssh.yml
  tags:
    - instances

- name: Prepare shared image
  ansible.builtin.import_tasks: image.yml
  tags:
    - image
    - instances

- name: Provision selected VMs
  ansible.builtin.include_tasks: instance.yml
  loop: "{{ selected_vms }}"
  loop_control:
    loop_var: vm
    label: "{{ vm.name }}"
  tags:
    - instances
