---
database_servers:
  postgres:
    container: postgres
    admin_user: admin
    password_secret: postgres_password

databases:
  - name: kaneo
    engine: postgres
  - name: authelia
    engine: postgres
  - name: outline
    engine: postgres
