---
compose_projects:
  - name: consul
  - name: traefik
    certificate: true
    certificate_domains:
      - home.arpa
      - auth.home.arpa
      - "*.svc.home.arpa"
      - "*.ops.home.arpa"
      - "*.{{ cloudflare_zone }}"
    files:
      - dynamic.yml
  - name: cadvisor
  - name: cloudflared
    templated_files:
      - config/config.yml
    tunnel_hostnames:
      - "outline.{{ cloudflare_zone }}"
      - "kaneo.{{ cloudflare_zone }}"
      - "auth.{{ cloudflare_zone }}"
