name: cadvisor

services:
  cadvisor:
    container_name: cadvisor
    image: ghcr.io/google/cadvisor:v0.60.5
    ports:
      - "8081:8080/tcp"
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    restart: unless-stopped
