---
compose_projects:
  - name: glance
    environment:
      KANEO_HOSTNAME: "{{ public_hostnames.kaneo }}"
      OUTLINE_HOSTNAME: "{{ public_hostnames.outline }}"
    files:
      - config/glance.yml
