---
compose_projects:
  - name: consul-agent
    prune_config: true
    files:
      - config/prometheus.hcl
      - config/glance.hcl
  - name: pihole
    environment:
      BASE_DOMAIN: "{{ base_domain }}"
  - name: prometheus
    files:
      - config/prometheus.yml
    data_directories:
      - path: data
        owner: "65534"
        group: "65534"
        mode: "0750"
  - name: glance
    environment:
      KANEO_HOSTNAME: "{{ public_hostnames.kaneo }}"
      OUTLINE_HOSTNAME: "{{ public_hostnames.outline }}"
    files:
      - config/glance.yml
  - name: cadvisor
