---
tailscale_advertised_routes:
  - 10.10.10.0/24
  - 10.10.20.0/24
  - 10.10.30.0/24
vm_definition:
  name: mgmt-01
  network: br-mgmt
  mac: '52:54:00:10:00:10'
  address: 10.10.10.10
  memory_mb: 2048
  vcpus: 2
  disk_gb: 20
