---
- name: Configure bridges and DHCP
  ansible.builtin.import_tasks: bridges.yml
  tags:
    - bridges

- name: Configure DHCP reservations
  ansible.builtin.import_tasks: reservations.yml
  tags:
    - reservations

- name: Configure routing
  ansible.builtin.import_tasks: routing.yml
  tags:
    - routing

- name: Configure NAT
  ansible.builtin.import_tasks: nat.yml
  tags:
    - nat
