name: pihole

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.07.2
    ports:
      - "10.10.10.10:53:53/tcp"
      - "10.10.10.10:53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: Asia/Singapore
      FTLCONF_dns_listeningMode: ALL
      FTLCONF_misc_dnsmasq_lines: |-
        address=/home.arpa/10.10.20.10
        address=/algebananazzzzz.com/10.10.20.10
        server=/consul/10.10.20.10#8600
    volumes:
      - ./data:/etc/pihole
    restart: unless-stopped
