---
- name: Create registrator directory
  ansible.builtin.file:
    path: "{{ compose_root }}/registrator"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Write registrator Compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ compose_root }}/registrator/compose.yml"
    owner: root
    group: root
    mode: "0640"

- name: Start registrator
  community.docker.docker_compose_v2:
    project_src: "{{ compose_root }}/registrator"
    remove_orphans: true
    wait: true
