---
all:
  children:
    hypervisors:
      hosts:
        host:
          ansible_host: 100.116.110.63
          ansible_port: 2222
    service_vms:
      hosts:
        svc-proxy-01:
          ansible_host: 10.10.20.10
        svc-01:
          vm_network: br-svc
          vm_mac: "52:54:00:20:00:11"
        svc-db-01:
          vm_network: br-svc
          vm_mac: "52:54:00:20:00:12"
        svc-apps-01:
          vm_network: br-svc
          vm_mac: "52:54:00:20:00:13"
    docker_hosts:
      children:
        hypervisors:
        service_vms:
        management:
    internal_ca_trust_hosts:
      hosts:
        svc-proxy-01:
        svc-01:
        svc-db-01:
        svc-apps-01:
    management:
      hosts:
        mgmt-01:
          ansible_host: 10.10.10.10
    workstations:
      hosts:
        weidong-xps-15-9530:
          ansible_connection: local
