[hypervisor]
hv-01

[management]
mgmt-01

[service]
svc-proxy-01
svc-db-01
svc-apps-01

[vm:children]
management
service

[docker_hosts:children]
hypervisor
vm

[pihole]
mgmt-01

[consul_server]
svc-proxy-01

[tailscale]
mgmt-01

[prometheus]
mgmt-01

[postgres]
svc-db-01

[redis]
svc-db-01

[mongo]
svc-db-01

[traefik]
svc-proxy-01

[cloudflared]
svc-proxy-01

[authelia]
svc-apps-01

[applications]
mgmt-01
svc-apps-01

[local]
weidong-xps-15-9530
