name: kaneo

services:
  kaneo:
    container_name: kaneo
    image: ghcr.io/usekaneo/kaneo:latest
    environment:
      DATABASE_URL: postgresql://admin:${POSTGRES_PASSWORD}@postgres.service.consul:5432/kaneo
      AUTH_SECRET: ${AUTH_SECRET}
      KANEO_CLIENT_URL: https://kaneo.svc.home.arpa
    ports:
      - "5173:5173/tcp"
    restart: unless-stopped
