---
admin_user: song
ansible_user: "{{ admin_user }}"
hypervisor_host: "{{ groups['hypervisor'] | first }}"
static_secret_values:
  postgres_password: "{{ lookup('ansible.builtin.env', 'POSTGRES_PASSWORD') }}"
  redis_password: "{{ lookup('ansible.builtin.env', 'REDIS_PASSWORD') }}"
  authelia_user_password: "{{ lookup('ansible.builtin.env', 'AUTHELIA_USER_PASSWORD') }}"
database_defaults:
  service: postgres
  host: svc-db-01
  user: admin
  password_secret: postgres_password
cloudflare_api_url: https://api.cloudflare.com/client/v4
cloudflare_zone: algebananazzzzz.com
cloudflare_tunnel_name: homelab
cloudflare_api_token: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_API_TOKEN') }}"
cloudflare_tunnel_secret: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_TUNNEL_SECRET') }}"
