---
admin_user: song
ansible_user: "{{ admin_user }}"
hypervisor_host: "{{ groups['hypervisor'] | first }}"
base_domain: algebananazzzzz.com

tls_certificate_domains:
  - home.arpa
  - auth.home.arpa
  - "*.svc.home.arpa"
  - "*.ops.home.arpa"
  - "*.{{ base_domain }}"

cloudflare:
  tunnel_name: homelab
  api_token: "{{ cloudflare_api_token }}"
  tunnel_secret: "{{ cloudflare_tunnel_secret }}"
