---
ansible_user: "{{ admin_user }}"
ansible_ssh_common_args: >-
  -o ProxyCommand="ssh -p {{ hostvars['host'].ansible_port }} {{ admin_user }}@{{ hostvars['host'].ansible_host }} nc %h %p"
network_dns_server: 10.10.20.1
