---
ansible_ssh_common_args: >-
  -o ProxyCommand="ssh -p {{ hostvars['host'].ansible_port }} {{ admin_user }}@{{ hostvars['host'].ansible_host }} nc %h %p"
vm_network: "{{ vm_definition.network }}"
vm_mac: "{{ vm_definition.mac }}"
compose_root: /opt/compose
