---
- name: Deploy Consul server
  hosts: consul_server
  gather_facts: false
  become: true

  roles:
    - core/consul

- name: Deploy Consul agents
  hosts: vm:!consul_server
  gather_facts: false
  become: true

  roles:
    - core/consul

- name: Configure Tailscale
  hosts: tailscale
  gather_facts: true
  become: true

  roles:
    - core/tailscale
