---
- name: Deploy Docker Compose projects
  hosts: docker_hosts
  gather_facts: true
  become: true

  pre_tasks:
    - name: Configure service VM DNS
      ansible.builtin.include_role:
        name: network
        tasks_from: client_dns
      when: network_dns_server is defined

  roles:
    - docker
