---
- name: Configure homelab infrastructure
  hosts: hypervisor
  gather_facts: true
  become: true

  roles:
    - role: host
      tags:
        - host
    - role: network
      tags:
        - network
