---
- name: Deploy Komodo Core
  hosts: komodo_core
  gather_facts: false
  become: true

  roles:
    - komodo/core

- name: Deploy Komodo Periphery
  hosts: komodo_periphery
  gather_facts: false
  become: true

  roles:
    - komodo/periphery
