---
- name: Issue internal certificates and deploy Traefik
  hosts: traefik
  gather_facts: false
  become: true

  roles:
    - proxy/internal_ca
    - proxy/traefik

- name: Trust the internal certificate authority
  hosts: vm
  gather_facts: false
  become: true

  tasks:
    - name: Install the internal CA
      ansible.builtin.include_role:
        name: proxy/internal_ca
        tasks_from: trust
