name: docmost

services:
  docmost:
    container_name: docmost
    image: docmost/docmost:0.95.0
    environment:
      APP_URL: http://docmost.home.arpa
      APP_SECRET: ${DOCMOST_APP_SECRET}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres.service.consul:5432/docmost?schema=public
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis.service.consul:6379/1
      STORAGE_DRIVER: local
    ports:
      - "3000:3000/tcp"
    volumes:
      - docmost-data:/app/data/storage
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://127.0.0.1:3000/"]
      interval: 10s
      timeout: 5s
      retries: 30
    restart: unless-stopped

volumes:
  docmost-data:
    name: homelab-docmost-data
